stages:
  - preparation

composer:
  stage: preparation
  image: docker-repository.intern.neusta.de/composer:2
  script:
    - ls -la
  only:
    - feature/NSDDARTY-55-Pipeline


# - container
# - composer
# - php
# - code / tests
