stages:
  - preparation
  - unittests
  - quality-check
  - deploy

variables:
  ITEST_HOST_IP: 172.31.193.127
  ITEST_USER: darty

.docker-repo-login: &docker-repo-login
  - echo $DOCKERREPOPASSWD | docker login -u docker-repo-user --password-stdin docker-repository.intern.neusta.de
  - echo $DOCKERREPOPASSWD | docker login -u docker-repo-user --password-stdin docker-repository.intern.neusta.de:18443

.snippet-configure-ssh: &snippet-configure-ssh
  - eval $(ssh-agent -s)
  - echo "${ITEST_PRIVATE_KEY}" | ssh-add - > /dev/null
  - mkdir -p ~/.ssh/

composer:
  stage: preparation
  image: docker-repository.intern.neusta.de/composer:2
  script:
    - ls -la
    - cd symfony/my_project_directory/
    - composer install --no-interaction --no-scripts --ignore-platform-reqs
    - ls -la
  artifacts:
    paths:
      - symfony/my_project_directory/vendor

build-php-image:
  stage: preparation
  dependencies: []
  before_script:
    - *docker-repo-login
  script:
    - docker build -t docker-repository.intern.neusta.de/darty2/php:latest -t docker-repository.intern.neusta.de:18443/darty2/php:latest ./.docker/php
    - docker push docker-repository.intern.neusta.de:18443/darty2/php:latest

build-web-image:
  stage: preparation
  dependencies: []
  before_script:
    - *docker-repo-login
  script:
    - docker build -t docker-repository.intern.neusta.de/darty2/web:latest -t docker-repository.intern.neusta.de:18443/darty2/web:latest ./.docker/web
    - docker push docker-repository.intern.neusta.de:18443/darty2/web:latest

php-unit:
 stage: unittests
 image: docker-repository.intern.neusta.de/darty2/php:latest
 script:
   - cd symfony/my_project_directory/
   - vendor/phpunit/phpunit/phpunit
 artifacts:
   paths:
     - symfony/my_project_directory/reports

sonar:
  stage: quality-check
  image: docker-repository.intern.neusta.de/sonarsource/sonar-scanner-cli:neusta
  script:
#    - sed -i 's|/builds/.*/sbock/darty2|'$CI_PROJECT_DIR'|g' Source/reports/clover-coverage.xml
    - "sonar-scanner -Dsonar.projectBaseDir=$CI_PROJECT_DIR
        -Dsonar.projectVersion=$CI_PIPELINE_ID
        "
  dependencies:
    - php-unit
  only:
    - develop

copy-code:
  stage: deploy
  only:
    - develop
  needs:
    - composer
  image: docker-repository.intern.neusta.de/eeacms/rsync:2.3
  before_script:
    - *snippet-configure-ssh
    - ssh-keyscan -t rsa $ITEST_HOST_IP > ~/.ssh/known_hosts
  script:
    - rsync -rltgoDH . darty@172.31.193.127:/home/darty/app/

pull-images:
  stage: deploy
  only:
    - develop
  before_script:
    - *snippet-configure-ssh
    - ssh-keyscan -t rsa $ITEST_HOST_IP > ~/.ssh/known_hosts
  script:
    - ssh $ITEST_USER@$ITEST_HOST_IP 'docker pull docker-repository.intern.neusta.de/darty2/php:latest'
    - ssh $ITEST_USER@$ITEST_HOST_IP 'docker pull docker-repository.intern.neusta.de/darty2/web:latest'

restart-docker:
  stage: deploy
  only:
    - develop
  before_script:
    - *snippet-configure-ssh
    - ssh-keyscan -t rsa $ITEST_HOST_IP > ~/.ssh/known_hosts
  script:
    - ssh $ITEST_USER@$ITEST_HOST_IP 'cd app && docker compose down && docker compose up -d'
