version: '3.4'
services:
  php:
    image: "darty2/php:latest"
    build:
      context: ./.docker/php
      args:
        docker_registry: ${DOCKER_REGISTRY:-docker-repository.intern.neusta.de}
    container_name: ${DOCKER_CONTAINER_TAG}-php
    volumes:
      - ./symfony/:/var/www/html/
    networks:
      - darty2
    environment:
      XDEBUG_MAX_NESTING_LEVEL: 400
      XDEBUG_DISCOVER_CLIENT_HOST: true
      XDEBUG_MODE: debug,trace,coverage
      XDEBUG_START_WITH_REQUEST: trigger
      XDEBUG_CLIENT_HOST: host.docker.internal
      XDEBUG_IDEKEY: PHPSTORM
    expose:
      - 9003 # xdebug 3 port!

  web:
    env_file:
      - .env
    image: "darty2/web:latest"
    build:
      context: ./.docker/web
      args:
        docker_registry: ${DOCKER_REGISTRY:-docker-repository.intern.neusta.de}
    container_name: ${DOCKER_CONTAINER_TAG}-web
    depends_on:
      - php
    volumes:
      - ./symfony/:/var/www/html/
    ports:
      - "8081:80"
    networks:
      - darty2

  mariadb:
    image: 'mariadb:10.9.3'
    environment:
      - MARIADB_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MARIADB_DATABASE=${DATABASE_NAME}
      - MARIADB_USER=${DATABASE_USER}
      - MARIADB_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - '3306'
    networks:
      - darty2
networks:
  darty2:
    ipam:
      config:
        - subnet: 10.255.255.80/28
